---
application:
  name: "moebest"
  project: "moebest"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "moebest"
  version: "5.7"
routers:
- name: "main-moebest"
- branch: main
    domain: www.moeyy.tech
  routes:
  - application_name: "moebest"
    paths:
    - "/*"
