---
application:
  name: "moebest"
  project: "moe‘s space"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "moebest"
  version: "5.7"
routers:
- name: "main-moebest"
  routes:
  - application_name: "moebest"
    paths:
    - "/*"
