---
application:
  name: "ghost"
  project: "moe‘s space"
  organization: "QoveryCommunity"
  storage:
  - name: "ghost-data"
    size: "5GB"
    type: "ssd"
    mount_point: "/var/lib/ghost/content"
routers:
- name: "ghost-router"
custom_domains:
  - branch: main
    domain: www.moeyy.tech
  routes:
  - application_name: "ghost"
    paths:
    - "/"
